convert pd.Timestamp val to pydatetime
This patch is to fix the test failures caused by the previous PR.

The failures were caused by passing pd.Timestamp values directly to sqlalchemy:

AttributeError: 'MySQLConverter' object has no attribute '_timestamp_to_mysql'

Surprisingly, a pd.Timestamp val is an instance of datetime.datetime:

>>> import datetime
>>> import pandas as pd
>>> isinstance(pd.Timestamp('today'), datetime.datetime)
True

This PR converts pd.Timestamp to python datetime.datetime obj by calling to_pydatetime.